services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: vavavava
      MYSQL_USER: root
      MYSQL_PASSWORD: zoirjon0211@
      MYSQL_DATABASE: restdb
    ports:
      - "3307:3306"