spring.application.name=spring-6-rest-mvc
logging.level.muslimdev.spring6restmvc=debug
logging.level.org.zalando.logbook=trace


spring.profiles.active=localmysql
spring.flyway.enabled=false
spring.docker.compose.enabled=false
spring.threads.virtual.enabled=false
spring.cache.cache-names=beerCache,beerListCache,clientCache,clientList
#spring.security.user.name=user
#spring.security.user.password=password

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
management.endpoint.health.probes.enabled=true
management.health.readinessstate.enabled=true


#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=V1__init-mysql-database.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=V1__init-mysql-database.sql


